service: urlShortener

provider:
  name: aws
  runtime: rust
  memorySize: 128
  plugins:
    - serverless-rust

package:
  individually: true

functions:
  getKey:
    handler: get_key # required, handler set in AWS Lambda
    name: urlshortener-get-key # optional, Deployed Lambda name
    description: Description of what the lambda function does # optional, Description to publish to AWS
    runtime: provided.al2 # optional overwrite, default is provider runtime
    events:
      - http:
          path: get
          method: post
    environment:
      REDIS_ADDRESS: ""
      REDIS_POST: ""
      REDIS_PASSWORD: ""
      REDIS_TLS: ""

  setKey:
    handler: set_key # required, handler set in AWS Lambda
    name: urlshortener-set-key # optional, Deployed Lambda name
    description: Description of what the lambda function does # optional, Description to publish to AWS
    runtime: provided.al2 # optional overwrite, default is provider runtime
    events:
      - http:
          path: set
          method: post
    environment:
      REDIS_ADDRESS: ""
      REDIS_POST: ""
      REDIS_PASSWORD: ""
      REDIS_TLS: ""

resources:
  Resources:
    NewResource:
      Type: AWS::APIGATEWAY
      Properties:
        name: url_shortener